###

POST http://localhost:3000/auth/register
Content-Type: "application/json"

{
    "email": "user@gmail.com",
    "password": "password",
    "confirmPassword": "password",
    "name": "admin"
}

###

POST http://localhost:3000/auth/login
Content-Type: "application/json"

{
    "email": "admin@gmail.com",
    "password": "admin123"
}

###

GET http://localhost:3000/panel