###

POST http://localhost:3000/auth/register
Content-Type: "application/json"

{
    "email": "admin@gmail.com",
    "password": "admin123",
    "confirmPassword": "admin123",
    "name": "admin"
}

###

POST http://localhost:3000/auth/login
Content-Type: "application/json"

{
    "email": "admin@gmail.com",
    "password": "admin123"
}

###

GET http://localhost:3000/admin
Content-Type: "application/json"

###

GET http://localhost:3000/user
Content-Type: "application/json"
